title: "cmh9101 Paper Review"
description: "3DGS, NeRF, Diffusion 논문 및 코드 분석"
url: "https://cmh9101.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-include-cache

locale: "ko-KR"

author:
  name: "cmh9101"
  bio: "뚱뚱뚱."
  location: "Seoul, Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cmh9101"
